### ISSUE TITLE
TODO: Add Negative feedback

### ISSUE THREAD

**Issue by proffapt** [proffapt/fERP#2]
- [x] Analyse the feedback form and get object names
- [x] Type-out the code
- [x] Type-out the negative feedback

**Comment by proffapt** [comment]
Done in https://github.com/proffapt/fERP/commit/aa67f25df2aa925cc1f2e33ce67eaada07ed175f

**Comment by proffapt** [comment]
Done in https://github.com/proffapt/fERP/commit/aa67f25df2aa925cc1f2e33ce67eaada07ed175f
